OpenLiberty/guide-microprofile-health

README.adoc

Additional ID edits.

---

README.adoc
finish/pom.xml
finish/src/main/liberty/config/server.xml
start/pom.xml
start/src/main/liberty/config/server.xml

The paragraph starting with  "This time, you are.." @Kubik42 can fix it.

Fixed feedback from final review

---

README.adoc

Altered README to keep consistent with other guides

---

finish/src/test/java/it/io/openliberty/guides/health/HealthTestUtil.java

Minor IDE warning resolved

---

finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java

OpenLiberty/guides-common#95
OpenLiberty/guides-common#137

Refactor inventory

---

finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryHealth.java
finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
start/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
start/src/test/java/it/io/openliberty/guides/health/HealthTestUtil.java

- Removed unused imports
- Reorganized imports to import specific classes instead of java.util.*
- Proper use of static method instead of instantiating InventoryUtils

Fix imports, use of static method

---

finish/pom.xml
start/pom.xml

Issue: OpenLiberty/guides-common#268
Tested on Java 8 and 11

Updated Dependencies

---

finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java

Addressing: https://github.com/OpenLiberty/guide-microprofile-health/issues/79

Updated InventoryResource.java so error messages show in JSON format

---

README.adoc
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java

Merge qa to master: mp3 update

---

README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/inventory/InventoryReadinessCheck.java
finish/src/main/java/io/openliberty/guides/system/SystemLivenessCheck.java
finish/src/main/java/io/openliberty/guides/system/SystemReadinessCheck.java
finish/src/main/liberty/config/server.xml
finish/src/test/java/it/io/openliberty/guides/health/HealthTest.java
start/pom.xml
start/src/main/liberty/config/server.xml

https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308

hotspot & name convention update

---

README.adoc
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java

- Updated guide to dev mode
- The dev mode content was merged from this PR: https://github.com/OpenLiberty/guide-microprofile-health/pull/91..

Qa to Master: dev mode

---

README.adoc
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java

Merge qa to master: update dependencies version

---

README.adoc
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java

Merge qa to master: update to mp 3.2

---

finish/pom.xml
start/pom.xml

Issue: https://github.com/OpenLiberty/guides-common/issues/419
Tested with changed dependency, looks good

change `junit-jupiter-engine` to `junit-jupiter`

---

README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/inventory/InventoryLivenessCheck.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryReadinessCheck.java
finish/src/main/java/io/openliberty/guides/system/SystemLivenessCheck.java
finish/src/main/java/io/openliberty/guides/system/SystemReadinessCheck.java
finish/src/main/liberty/config/server.xml
finish/src/main/webapp/index.html
finish/src/test/java/it/io/openliberty/guides/health/HealthIT.java
start/pom.xml
start/src/main/liberty/config/server.xml
start/src/main/webapp/index.html

https://github.com/openliberty/guide-microprofile-health/issues/108

update guide to mphealth 2.2

---

README.adoc

Addressing: https://github.com/OpenLiberty/guide-microprofile-health/issues/114.

remove unused hotspot

---

.github/workflows/test.yml
.travis.yml

Merge qa to master: no need to run test if just update README.adoc

---

.github/workflows/test.yml

Sync the change from master to qa

---

.github/workflows/triggerConversion.yml

* Added Conversion action
* Update triggerConversion.yml
Co-authored-by: Jakub F Pomykala <Jakub.Pomykala@ibm.com>

Merge qa to master: Added Conversion action (#139)

---

.github/workflows/triggerConversion.yml

* Added Conversion action
* Update triggerConversion.yml
* Update triggerConversion.yml
* Added space at line 28
authored-by: Jakub F Pomykala <Jakub.Pomykala@ibm.com>

Merge qa to master: fixing TriggerConversion (#141)

---

.github/workflows/test.yml
README.adoc

* Update README.adoc
* Update test.yml

Merge qa to master: Add cloud-hosted guide instructions (#143)

---

README.adoc

* Updating Readme.adoc from Austin's feedback in test plan
* Update README.adoc
Co-authored-by: Gilbert Kwan <gkwan@ca.ibm.com>

Merge qa to master: Updating Readme.adoc from Austin's feedback in test plan (#146)

---

README.adoc

Update README.adoc (#148)
